In [0]:
import numpy as np

# Atividades para treino numpy
(Gerados pelo chatGpt)

## Iniciante:

In [0]:
# Crie um array de 10 zeros.

np.zeros(10)

Out[2]: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# Crie um array de 10 números inteiros aleatórios entre 1 e 100.

np.random.randint(1, 100, 10)

Out[11]: array([19, 39, 64, 54, 91, 88, 95, 76, 47, 69])

In [0]:
# Crie um array com valores de 0 a 20 com passo 2.

np.random.randint(1, 100, 20)

Out[13]: array([25, 18, 29, 74, 80, 77, 58, 30, 64, 11, 25, 35, 41, 79, 58, 83, 37,
        8,  7, 57])

In [0]:
# Crie uma matriz 3x3 contendo apenas números 1.

np.ones((3,3), dtype=int)

Out[18]: array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
# Crie uma matriz identidade 4x4.

np.identity(4)

Out[20]: array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
# Calcule a média, mediana e desvio padrão de um array.

arr = np.arange(1, 11)

print(arr.mean())
print(np.median(arr))
print(np.std(arr))

5.5
5.5
2.8722813232690143


In [0]:
# Reshape um array de 1D para 2D (ex: de (9,) para (3,3)).
arr = np.arange(9)
arr.reshape(3,3)

Out[32]: array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Intermediário

In [0]:
# Multiplique elemento a elemento duas matrizes 3x3.

arr1 = np.arange(1, 10).reshape(3,3)
arr2 = arr1[::-1]

print(arr1*arr2)

[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [0]:
# Filtre os números pares de um array aleatório de 20 elementos.

arr = np.random.randint(1, 100, 20)
isEven = arr % 2 == 0

print(arr[isEven])


[70  2 92 60 20 30  6 16 98 12 70 68 66 76]


In [0]:
# Substitua todos os valores maiores que 50 por 50 em um array aleatório.

arr = np.random.randint(1, 100, 20)
arr[arr > 50] = 50
print(arr)

[50 50 24 50 50 50 45 50 50 38  6 50 50  1 29 50 47 50 50 50]


In [0]:
# Crie uma matriz 5x5 com números aleatórios e zere as bordas.

arr = np.arange(25).reshape(5,5)

arr[0, :] = 0  
arr[-1, :] = 0 
arr[:, 0] = 0  
arr[:, -1] = 0 

arr



Out[61]: array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  7,  8,  0],
       [ 0, 11, 12, 13,  0],
       [ 0, 16, 17, 18,  0],
       [ 0,  0,  0,  0,  0]])

In [0]:
# Encontre os índices dos elementos maiores que a média em um array.

arr = np.arange(1, 101)

bigger_mean = arr > arr.mean()

print(np.where(bigger_mean))

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)


In [0]:
# Use slicing para extrair uma submatriz de uma matriz 6x6.

arr = np.arange(1,37).reshape(6,6)
arr[3:, 3:]

Out[67]: array([[22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

## Avançado

In [0]:
# Crie uma matriz 10x10 com valores aleatórios e encontre o maior valor de cada linha.

arr = np.arange(1, 101).reshape(10,10)
bigger_values = np.max(arr, axis=1)
bigger_values

Out[72]: array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])